[project]
name = "Matrix-Analysis"
version = "0.1.0"
description = "data analysis"
requires-python = ">=3.10"

[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
numpy = "^1.26.4"
matplotlib = "^3.9.4"
pandas = "^2.2.3"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
